import { User, Property, Lease, InventoryReport, Payment, Conversation } from '../types';

export const INITIAL_USER_LANDLORD: User = {
  id: 'usr_landlord_default',
  name: 'Propriétaire',
  phone: '',
  role: 'LANDLORD',
  verificationStatus: 'PENDING',
  createdAt: '2026-01-15T10:00:00Z',
};

export const INITIAL_USER_TENANT: User = {
  id: 'usr_tenant_default',
  name: 'Locataire',
  phone: '',
  role: 'TENANT',
  verificationStatus: 'PENDING',
  createdAt: '2026-03-01T14:30:00Z',
};

export const INITIAL_USERS: User[] = [
  INITIAL_USER_LANDLORD,
  INITIAL_USER_TENANT,
  {
    id: 'usr_landlord_fatou',
    name: 'Madame Fatou Kane',
    phone: '+221 76 544 33 22',
    role: 'LANDLORD',
    verificationStatus: 'VERIFIED',
    subscriptionStatus: 'PRO',
    subscriptionPlan: 'ANNUAL',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'usr_landlord_demba',
    name: 'Demba Ba',
    phone: '+221 70 889 22 11',
    role: 'LANDLORD',
    verificationStatus: 'VERIFIED',
    subscriptionStatus: 'PRO',
    subscriptionPlan: 'MONTHLY',
    createdAt: '2026-03-10T11:00:00Z',
  },
  {
    id: 'usr_admin_super',
    name: 'Administrateur ImmoConnect',
    phone: '+221 77 000 00 00',
    role: 'ADMIN',
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop_mermoz_f3',
    ownerId: 'usr_landlord_agence',
    ownerName: 'Agence ImmoConnect',
    ownerPhone: '+221 77 000 00 00',
    ownerVerified: true,
    title: 'Appartement F3 Moderne Lumineux',
    description: 'Magnifique appartement F3 avec finition haut de gamme, grand séjour ventilé, cuisine aménagée avec placards, master bedroom avec salle de bain contiguë et balcon avec vue sur Mermoz. Immeuble sécurisé 24h/24 avec réservoir d’eau et surpresseur.',
    region: 'Dakar',
    neighborhood: 'Mermoz',
    city: 'Dakar',
    type: 'APPARTEMENT',
    rooms: 3,
    price: 250000,
    chargesIncluded: true,
    isAvailable: true,
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    ],
    approxLocation: 'À 150m de l\'Ancienne Piste, Mermoz Pyrotechnie',
    createdAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'prop_saly_villa',
    ownerId: 'usr_landlord_agence',
    ownerName: 'Agence ImmoConnect',
    ownerPhone: '+221 77 000 00 00',
    ownerVerified: true,
    title: 'Villa de Standing avec Piscine à Saly',
    description: 'Superbe villa contemporaine à Saly Portudal avec piscine privée, jardin tropical arboré, 3 chambres climatisées avec salles de bains en suite, terrasse couverte et garage fermé. Sécurité 24h/24. Proche plage et golf.',
    region: 'Thiès',
    neighborhood: 'Saly Portudal',
    city: 'Mbour',
    type: 'MAISON',
    rooms: 4,
    price: 550000,
    chargesIncluded: true,
    isAvailable: true,
    photos: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    approxLocation: 'Saly Niakh Niakhal, à 300m de la plage',
    createdAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'prop_saint_louis_maison',
    ownerId: 'usr_landlord_fatou',
    ownerName: 'Madame Fatou Kane',
    ownerPhone: '+221 76 544 33 22',
    ownerVerified: true,
    title: 'Maison Coloniale de Charme à l\'Île de Saint-Louis',
    description: 'Demeure historique entièrement rénovée située sur la mythique Île de Saint-Louis. 3 pièces spacieuses avec hauts plafonds, terrasse intérieure patio ombreuse, vue sur le fleuve Sénégal.',
    region: 'Saint-Louis',
    neighborhood: 'Île de Saint-Louis',
    city: 'Saint-Louis',
    type: 'MAISON',
    rooms: 3,
    price: 280000,
    chargesIncluded: false,
    isAvailable: true,
    photos: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80',
    ],
    approxLocation: 'Près du Pont Faidherbe, Île de Saint-Louis',
    createdAt: '2026-04-12T14:15:00Z',
  },
  {
    id: 'prop_cap_skirring_bungalow',
    ownerId: 'usr_landlord_demba',
    ownerName: 'Demba Ba',
    ownerPhone: '+221 70 889 22 11',
    ownerVerified: true,
    title: 'Bungalow Bord de Mer Cap Skirring',
    description: 'Bungalow au charme casamanceis niché sous les cocotiers à Cap Skirring. Accès direct plage, 2 pièces meublées, brise marine permanente, havre de paix.',
    region: 'Ziguinchor',
    neighborhood: 'Cap Skirring',
    city: 'Oussouye',
    type: 'STUDIO',
    rooms: 2,
    price: 200000,
    chargesIncluded: true,
    isAvailable: true,
    photos: [
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    approxLocation: 'Zone Hôtelière Cap Skirring Beach',
    createdAt: '2026-05-01T09:30:00Z',
  },
  {
    id: 'prop_almadies_studio',
    ownerId: 'usr_landlord_agence',
    ownerName: 'Agence ImmoConnect',
    ownerPhone: '+221 77 000 00 00',
    ownerVerified: true,
    title: 'Studio Executive Meublé Almadies',
    description: 'Studio standing entièrement équipé aux Almadies. Lit Queen-size, climatisation inverter, Smart TV, Wi-Fi haut débit, kitchenette équipée, gardiennage et groupe électrogène. Idéal pour cadre expatrié ou séjour professionnel.',
    region: 'Dakar',
    neighborhood: 'Almadies',
    city: 'Dakar',
    type: 'STUDIO',
    rooms: 1,
    price: 450000,
    chargesIncluded: true,
    isAvailable: true,
    photos: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    approxLocation: 'Ruelle des Almadies, près de la Corniche Almadies',
    createdAt: '2026-04-01T11:20:00Z',
  },
  {
    id: 'prop_thies_f3',
    ownerId: 'usr_landlord_fatou',
    ownerName: 'Madame Fatou Kane',
    ownerPhone: '+221 76 544 33 22',
    ownerVerified: true,
    title: 'Appartement F3 Spacieux à Thiès Dixième',
    description: 'Appartement F3 moderne au quartier Dixième à Thiès. Quartier résidentiel très agréable, proche des écoles et commerces. 2 grandes chambres, séjour ventilé.',
    region: 'Thiès',
    neighborhood: 'Thiès Ville',
    city: 'Thiès',
    type: 'APPARTEMENT',
    rooms: 3,
    price: 150000,
    chargesIncluded: false,
    isAvailable: true,
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80',
    ],
    approxLocation: 'Thiès Dixième près de la VDN de Thiès',
    createdAt: '2026-05-18T16:00:00Z',
  },
  {
    id: 'prop_touba_maison',
    ownerId: 'usr_landlord_demba',
    ownerName: 'Demba Ba',
    ownerPhone: '+221 70 889 22 11',
    ownerVerified: true,
    title: 'Grande Maison Familiale à Touba',
    description: 'Vaste maison de 5 pièces à Touba Mosquée. Cour intérieure avec puits et surpresseur, 4 chambres, salon familial, idéale pour grande famille.',
    region: 'Diourbel',
    neighborhood: 'Touba',
    city: 'Mbacké',
    type: 'MAISON',
    rooms: 5,
    price: 180000,
    chargesIncluded: false,
    isAvailable: true,
    photos: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    ],
    approxLocation: 'Touba HLM, près de la Grande Mosquée',
    createdAt: '2026-06-05T12:00:00Z',
  },
];

export const INITIAL_LEASES: Lease[] = [];

export const INITIAL_INVENTORY_REPORTS: InventoryReport[] = [];

export const INITIAL_PAYMENTS: Payment[] = [];

export const INITIAL_CONVERSATIONS: Conversation[] = [];
